### ISSUE TITLE
Styling Issues

### ISSUE THREAD

**Issue by georgealexanderday** [dvcrn/chatgpt-ui#1]
Absolutely love the idea of this application so kudos to you. I'm just having a play round with the code and from initial clone I receive the following error:

```
`[ERROR] Could not resolve "highlight.js"

    js/app.js:24:17:
      24 │ import hljs from "highlight.js";
         ╵                  ~~~~~~~~~~~~~~

  You can mark the path "highlight.js" as external to exclude it from the bundle, which will remove this error.

1 error
[watch] build finished, watching for changes...
Error: Failed to find '../../node_modules/highlight.js/styles/googlecode.css'
  in [
    /Users/g/code/elixir/chatgpt-ui/assets/css
  ]
    at /snapshot/tailwindcss/node_modules/postcss-import/lib/resolve-id.js:35:13
    at async LazyResult.runAsync (/snapshot/tailwindcss/node_modules/postcss/lib/lazy-result.js:396:11)
    at async Object.watch (/snapshot/tailwindcss/lib/cli/build/plugin.js:359:13)
    at async build (/snapshot/tailwindcss/lib/cli/build/index.js:40:9)
`
```

Am I missing something obvious here? Apologies if so - still learning.

**Comment by dvcrn** [comment]
Hey! Let me look into it but I think you just have to do yarn install or npm install. That should fix the error

(…. Which I forgot to add to the instructions)

**Comment by georgealexanderday** [comment]
Yep you are absolutely correct, appreciate the response!

**Comment by dvcrn** [comment]
Glad to hear it worked! I'll update the instructions 

If you have ideas or suggestions for improving this, let me know 🙂

**Comment by georgealexanderday** [comment]
Will do, I'm hopefully going to be building a project with it soon. Also really enjoyed your article on the elixir cli chatgpt, super helpful in my learning.
