### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by FreedomBen** [dvcrn/chatgpt-ui#5]
I wasn't able to find a license for this repo.  Is there a license already?  If not I would suggest MIT.  I'm happy to add one and send a PR

**Comment by dvcrn** [comment]
Good point, that’s an oversight 

I’ll try to add it when I have access to my machine again, but should be MIT

**Comment by FreedomBen** [comment]
Submitted #7 but feel free to ignore if you have something else in mind
